### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by masudr4n4** [kdeng00/Mear#50]
how can i install this app to my android phone? 
or where i can get the apk file?
can you cite any tutorial for my next time help

**Comment by kdeng00** [comment]
Hey @maaudrana , currently there is not an APK file and in order to get the app on your phone you need to build the app using android studio or using the adb tools from google in conjunction with the Kotlin tools if building from the command line. I can provide an APK file but this app is still in the development phase and has not reached the [development release milestone](https://github.com/amazing-username/Mear/milestone/2). 

Would you like for me to provide a development APK file anyways?

**Update**:
I see that you are a graphic designer, are wanting to help with creating asset resources?

**Comment by masudr4n4** [comment]
actually now i am trying to be app tester for bug-hunting besides design thats why asked for apk.
you can ask the designer who contributed here by providing logo to creat asset resources .
tnx

**Comment by kdeng00** [comment]
Hey @maaudrana, 

You still want the APK? I've been working on other projects this past week along and haven't got the chance to work on this project. This project is still one of my primary projects so it won't end anytime soon. Let me know and I'll upload it.
